name: qui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1 # Adicionando o pacote de cache de imagem

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1

# Configuração Elegante de Ícones
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true

  # Ícone principal (usado no iOS e como fallback para Androids antigos)
  image_path: "lib/app/assets/icon/icon.png"

  # --- Ícones Adaptativos para Android moderno ---
  # Cor de fundo do ícone. Pode ser "#FFFFFF" ou um asset.
  adaptive_icon_background: "#FFFFFF"

  # A imagem do seu logo (com transparência) que fica sobre o fundo.
  adaptive_icon_foreground: "lib/app/assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/data/
    - lib/app/assets/data/
